//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavisca.Frameworks.Serialization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SerializationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerializationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tavisca.Frameworks.Serialization.Resources.SerializationResources", typeof(SerializationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error during compression of an object. Check inner exception for further details..
        /// </summary>
        internal static string CompressionError_Generic {
            get {
                return ResourceManager.GetString("CompressionError_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration error has occurred, check inner exception for details..
        /// </summary>
        internal static string ConfigurationError_Generic {
            get {
                return ResourceManager.GetString("ConfigurationError_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error during decompression of an object. Check inner exception for further details..
        /// </summary>
        internal static string DecompressionError_Generic {
            get {
                return ResourceManager.GetString("DecompressionError_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tables returned by the target object had some invalid values. Following is the list of validation errors:.
        /// </summary>
        internal static string IInfluxDbData_Tables_Invalid {
            get {
                return ResourceManager.GetString("IInfluxDbData_Tables_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serialization setting type is invalid for {0} serializer. Expected type is {1}..
        /// </summary>
        internal static string InvalidSerializationSettingException {
            get {
                return ResourceManager.GetString("InvalidSerializationSettingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Cloning.
        /// </summary>
        internal static string Operation_DeepClone {
            get {
                return ResourceManager.GetString("Operation_DeepClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization.
        /// </summary>
        internal static string Operation_Deserialization {
            get {
                return ResourceManager.GetString("Operation_Deserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization.
        /// </summary>
        internal static string Operation_Serialization {
            get {
                return ResourceManager.GetString("Operation_Serialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred during {0} of {1}, the serializer type was {2}. Check inner exception for more details..
        /// </summary>
        internal static string SerializationException_Generic {
            get {
                return ResourceManager.GetString("SerializationException_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object sent for {0} was null..
        /// </summary>
        internal static string Target_Object_Null {
            get {
                return ResourceManager.GetString("Target_Object_Null", resourceCulture);
            }
        }
    }
}
